### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by Come-on-ZMZ** [Miraclelucy/dive_into_deep_learning#1]
No module named 'common'

**Comment by Li-4** [comment]
首先可以看到 py 文件中有通过路径引入 common 模块

```python
sys.path.append('D:\\pythonspace\\d2l\\d2lutil')  # 加入路径，添加目录
import common
```

你创建好路径并把作者的 `d2lutil` 文件夹复制到对应路径即可

**Comment by Tysiace** [comment]
> 首先可以看到 py 文件中有通过路径引入 common 模块
> 
> ```python
> sys.path.append('D:\\pythonspace\\d2l\\d2lutil')  # 加入路径，添加目录
> import common
> ```
> 
> 你创建好路径并把作者的 `d2lutil` 文件夹复制到对应路径即可

你好，麻烦问一下d2lutil文件夹在哪里

**Comment by Miraclelucy** [comment]
已经刷新了
